package net.Indyuce.mmocore.api;

public enum SoundEvent {
    LEVEL_UP,
    WARP_TELEPORT,
    WARP_CANCELLED,
    WARP_CHARGE,
    WARP_UNLOCK,
    SPELL_CAST_BEGIN,
    SPELL_CAST_END,
    CANT_SELECT_CLASS,
    SELECT_CLASS,
    LEVEL_ATTRIBUTE,
    RESET_ATTRIBUTES,
    RESET_SKILLS,
    NOT_ENOUGH_POINTS,
    CANCEL_QUEST,
    START_QUEST,
    CLOSE_LOOT_CHEST,
    LEVEL_SKILL_TREE_NODE,
    RESET_SKILL_TREE,
    CHANGE_SKILL_TREE;
}