name: Cloning

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - master  # Adjust this branch name based on your default branch

env:
  GITLAB_REPOSITORY_OWNER: 'phoenix-dvpmt'  # Replace with your GitLab repository information
  GITLAB_REPOSITORY: 'mmocore'
  GITLAB_BRANCH: 'master'  # Adjust this branch name based on your default branch
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_BRANCH: 'master'  # Adjust this branch name based on your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout GitHub repository
       uses: actions/checkout@v4.1.1
       with:
         repository: MediumCraft/MMOCore
    
    - name: Checkout GitLab repository
      run: |
        git clone --depth 1 https://gitlab.com/${{ env.GITLAB_REPOSITORY_OWNER }}/${{ env.GITLAB_REPOSITORY }} .
        cd MMOCore

    - name: Push Files
      run: |
        git add .
        git commit -m "Mirror Files"
        git push origin
