name: Cloning

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - master  # Adjust this branch name based on your default branch



env:
  GITLAB_REPOSITORY_OWNER: 'phoenix-dvpmt'  # Replace with your GitLab repository information
  GITLAB_REPOSITORY: 'mmocore'
  GITLAB_BRANCH: 'master'  # Adjust this branch name based on your default branch
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_BRANCH: 'master'  # Adjust this branch name based on your default branch

  GITHUB_TOKEN: ${{ secrets.MIRROR_ACCESS }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout GitHub repository
       uses: actions/checkout@v4.1.1
       with:
         repository: MediumCraft/MMOCore
    
     - name: Checkout GitLab repository
       run: |
         mkdir temp_directory
         git clone --depth 1 https://gitlab.com/${{ env.GITLAB_REPOSITORY_OWNER }}/${{ env.GITLAB_REPOSITORY }} temp_directory
         cp -r temp_directory/* .
         rm -rf temp_directory

     - name: Push Files
       run: |
         git config --global user.name "LeeHansHinLun"
         git config --global user.name "leehinlun.hans@gmail.com"
         
         git add .
         git commit -m "Mirror Files"
         git push origin
