display:
    name: 'Marksman'
    lore:
    - 'The marksman is a swift and accurate'
    - 'ranged fighter, never missing any arrow.'
    attribute-lore:
    - '&a+ &7Knockback Resistance'
    - '&a+ &7Speed Malus Reduction'
    - '&c- &7Max Health'
    - '&c- &7Movement Speed'
    - ''
    - '&8&lStrength'
    - '&7  Attack Damage: &c1 &7(+&c0&7)'
    - '&7  Attack Speed: &c4 &7(+&c0&7)'
    - '&7  Max Health: &c18 &7(+&c0&7)'
    - ''
    - '&8&lDexterity'
    - '&7  Knockback Resistance: &a15% &7(+&a1%&7)'
    - '&7  Movement Speed: &a21 &7(+&a0&7)'
    - '&7  Speed Malus Reduction: &a10% &7(+&a2%&7)'
    - ''
    - '&8&lIntellect'
    - '&7  Max Mana: &920 &7(+&90&7)'
    - '&7  Health Regen: &90.1 &7(+&90&7)'
    - '&7  Mana Regen: &90.166 &7(+&90&7)'
    item: BOW

# Players cannot go further than Lvl 100
max-level: 100

triggers:
    level-up:
    - 'command{format="mmocore admin skill-points give %player% 1"}'

mana:
    char: ■
    color: BLUE
    name: 'Mana'

cast-particle:
    particle: CRIT

skills:
    WEAKEN:
        level: 3
        max-level: 30
    COMBO_ATTACK:
        level: 7
        max-level: 30
    EVADE:
        level: 9
        max-level: 30
    MINOR_HEALINGS:
        level: 10
        max-level: 30

attributes:
    knockback-resistance:
        base: 15
        per-level: 1
    speed-malus-reduction:
        base: 10
        per-level: 2
    max-health:
        base: 18
        per-level: 0
    movement-speed:
        base: .21
        per-level: 0

# Experience sources for main class experience.
main-exp-sources:
- 'killmob{type=ZOMBIE;amount=1-3}'
- 'killmob{type=ENDERMAN;amount=6-9}'
